BUGFIX[HIGH](memcached): Add maintenance mode
open-io/ansible-role-openio-memcached pull request #4
Opened 2019-03-11 16:39 UTC by sebastienlapierre

##### SUMMARY 
See title

  ##### ISSUE TYPE
 #Uncomment one below
 - Bugfix Pull Request
 #- Docs Pull Request
 #- Feature Pull Request
 #- New Module Pull Request
 #- CI
 #- Tool

  ##### SCOPE (skeleton only)
 #Uncommend below
 - SDS
 #- OIOFS
 #- OIOFS_HA

  ##### IMPACT
 #Describe the impact of the change (N/A for no impact)
 N/A

  ##### ADDITIONAL INFORMATION
 #Include additional information to help people understand the change here
 #A step-by-step reproduction of the problem is helpful if there is no related issue
 #Paste verbatim command output below, e.g. before and after your change

2019-03-11 21:12 UTC, cdelgehier requested changes
* BUGFIX/MEDIUM(memcached): Add maintenance mode
* Wrong commit description
* Upgrade README.md

2019-03-14 16:28 UTC, cdelgehier requested changes

2019-03-14 16:28 UTC, cdelgehier commented on README.md
> +| `openio_memcached_provision_only` | `"False"` | Provision only without restarting / bootstrapping |
just `false`

2019-03-14 16:55 UTC, sebastienlapierre commented on README.md
> +| `openio_memcached_provision_only` | `"False"` | Provision only without restarting / bootstrapping |
done

2019-03-14 19:41 UTC, merged